### ISSUE TITLE
Travis build failing

### ISSUE THREAD

**Issue by CEKrause** [GeoscienceAustralia/Wind_multipliers#12]
Travis build failing. All nosetests passing for the develop branch when run from my local copy of the repo (which is exactly the same as the remote develop branch).

`
ERROR: Failure: ImportError (No module named Utilities.files)
Traceback (most recent call last):
  File "/home/travis/py/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/py/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/py/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/GeoscienceAustralia/Wind_multipliers/tests/test_openFiles.py", line 26, in <module>
    from Utilities.files import flStartLog
ImportError: No module named Utilities.files
`

**Comment by wcarthur** [comment]
No longer relevant
